# Generated by Django 4.1.2 on 2022-10-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app901', '0001_initial'),
    ]

    operations = [
    ]
