# Generated by Django 4.1.2 on 2022-11-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app901', '0006_rename_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
