# Generated by Django 4.1.2 on 2022-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app901', '0007_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='gato.png', null=True, upload_to=''),
        ),
    ]
